[pytest]
DJANGO_SETTINGS_MODULE = cvat.settings.testing
python_files = test_*.py
python_classes = TC*  Test*
python_functions = test_*

addopts =
    --cov=cvat/apps/lambda_manager
    --cov-report=term-missing
    --cov-report=xml:coverage.xml
    --cov-fail-under=85
